# docker-compose.yaml

services:
  kafka:
    image: apache/kafka:3.9.1
    container_name: kafka
    ports:
      - "9092:9092" # For communication between containers on the same network
      - "9093:9093" # For communication from the host machine
    environment:
      KAFKA_PROCESS_ROLES: "broker, controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # FastAPI Application Service
  fastapi-app:
    build:
      context: ./minio
      dockerfile: Dockerfile
    container_name: fastapi_service
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code  # Mount the app directory for live-reloading during development
    env_file:
      - .env.minio
    depends_on:
      - minio
    networks:
      - app-network

  # MinIO Service
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data # Persist data using a Docker volume
    env_file:
      - .env.minio
    command: server /data --console-address ":9001"
    networks:
      - app-network
  
  # 🔄 Postgres for MLflow Metadata
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlflow -d mlflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MLflow Server
  mlflow:
    build: ./mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - MLFLOW_TRACKING_URI=http://localhost:5000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    depends_on:
      postgres:
        condition: service_healthy # Waits for the healthcheck to pass
      minio:
        condition: service_started # MinIO starts fast, so 'started' is often enough
    networks:
      - app-network
    command: >
      sh -c "
      echo 'Attempting to create MinIO bucket...' &&
      awslocal --endpoint-url=http://minio:9009 s3 mb s3://mlflow || true &&
      echo 'Bucket check complete. Starting MLflow server...' &&
      mlflow server
      --backend-store-uri postgresql://mlflow:mlflow@postgres/mlflow
      --default-artifact-root s3://mlflow/
      --host 0.0.0.0
      --port 5000
      "

  # EDA Service
  # eda:
  #   build: ./eda_container
  #   ports:
  #     - "8010:8010"
  #   environment:
  #     - GATEWAY_URL=http://fastapi-app:8000
  #   depends_on:
  #     - fastapi-app
  #   networks:
  #     - app-network


  # Preprocessing Service (Producer)
  preprocess:
    build: ./preprocess_container
    ports:
      - "8020:8020"
    environment:
      - GATEWAY_URL=http://fastapi-app:8000
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PRODUCER_TOPIC_0=training-data
      - PRODUCER_TOPIC_1=inference-data

      - SCALER=StandardScaler
    depends_on:
      fastapi-app:
        condition: service_started
      kafka:
        condition: service_healthy
    networks:
      - common
      - app-network
    
  # Training Container (consumer/producer)
  # train:
  #   build: ./train_container
  #   ports:
  #     - "8021:8021"
  #   depends_on:
  #     mlflow:
  #       condition: service_started
  #     kafka:
  #       condition: service_healthy
  #   environment:
  #     - GATEWAY_URL=http://fastapi-app:8000
  #     - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  #     - CONSUMER_TOPIC=training-data
  #     - CONSUMER_GROUP_ID=train
  #     - PRODUCER_TOPIC=model-training
  #     - MLFLOW_TRACKING_URI=http://mlflow:5000
  #     - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
  #     - AWS_ACCESS_KEY_ID=minioadmin
  #     - AWS_SECRET_ACCESS_KEY=minioadmin

  #     - MODEL_TYPE=TCN
  #     - TRAIN_TEST_SPLIT=0.8
  #     - INPUT_SEQ_LEN=10
  #     - OUTPUT_SEQ_LEN=1
      
  #     - HIDDEN_SIZE=128
  #     - NUM_LAYERS=4
  #     - MODEL_DIM=128
  #     - NUM_HEADS=8
  #     - FEEDFORWARD_DIM=512
  #     - DROPOUT=0.1
  #     - LAYER_ARCHITECTURE=[32, 64, 128, 256]
  #     - KERNEL_SIZE=2

  #     - BATCH_SIZE=32
  #     - EPOCHS=50
  #     - EARLY_STOPPING=True
  #     - PATIENCE=30
  #     - LEARNING_RATE=0.001

  #   networks:
  #     - app-network

  nonml:
    build: ./nonML_container
    ports:
      - "8022:8022"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - GATEWAY_URL=http://fastapi-app:8000
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - CONSUMER_TOPIC=training-data
      - CONSUMER_GROUP_ID=nonml
      - PRODUCER_TOPIC=model-training

      - MODEL_TYPE=AUTOARIMA # (str) Options: PROPHET, AUTOARIMA, AUTOETS, AUTOTHETA, AUTOMFLES, AUTOTBATS
      - DOWNSAMPLING=0 # (str) 0 for original periodicity
      - SEASON_LENGTH=30 # (int) Recommend smallest relevant seasonality

      # - TRIMS=["down"]

    networks:
      - app-network

  # Inference Container (consumer/producer)
  inference:
    build: ./inference_container
    ports:
      - "8023:8023"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - GATEWAY_URL=http://fastapi-app:8000
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - TQDM_DISABLE=1 # Disable tqdm progress bars in the logs
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - CONSUMER_TOPIC_0=inference-data
      - CONSUMER_TOPIC_1=model-training
      - CONSUMER_GROUP_ID=batch-forecasting
      - PRODUCER_TOPIC=performance-eval

      - SAMPLE_IDX=0 # (int) Index of data point from which to begin inference
      - INFERENCE_LENGTH=4070 # (int) Length of the inference sequence
    networks:
      - common
      - app-network

# Define the network
networks:
  common:
    external: true
  app-network:
    driver: bridge

volumes:
  minio_data:

  
