# docker-compose.yaml

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092" # For communication between containers on the same network
      - "9093:9093" # For communication from the host machine
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # FastAPI Application Service
  fastapi-app:
    build:
      context: ./minio_container
      dockerfile: Dockerfile
    container_name: fastapi_service
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code  # Mount the app directory for live-reloading during development
    env_file:
      - .env.minio
    depends_on:
      - minio
    networks:
      - app-network

  # MinIO Service
  minio:
    image: minio/minio:latest
    container_name: minio_storage_service
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data # Persist data using a Docker volume
    env_file:
      - .env.minio
    command: server /data --console-address ":9001"
    networks:
      - app-network
  
  # 🔄 Postgres for MLflow Metadata
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlflow -d mlflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MLflow Server
  mlflow:
    build: ./mlflow_container
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    depends_on:
      postgres:
        condition: service_healthy # Waits for the healthcheck to pass
      minio:
        condition: service_started # MinIO starts fast, so 'started' is often enough
    networks:
      - app-network
    command: >
      sh -c "
      echo 'Attempting to create MinIO bucket...' &&
      awslocal --endpoint-url=http://minio:9000 s3 mb s3://mlflow || true &&
      echo 'Bucket check complete. Starting MLflow server...' &&
      mlflow server
      --backend-store-uri postgresql://mlflow:mlflow@postgres/mlflow
      --default-artifact-root s3://mlflow/
      --host 0.0.0.0
      --port 5000
      "

  # EDA Service
  data_analyzer:
    build: ./eda_container
    ports:
      - "8010:8010"
    environment:
      - GATEWAY_URL=http://fastapi-app:8000
    depends_on:
      - fastapi-app
    networks:
      - app-network


  # Preprocessing Service (Producer)
  preprocesser:
    build: ./preprocessing_container
    environment:
      - GATEWAY_URL=http://fastapi-app:8000
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PRODUCER_TOPIC_0=training-data
      - PRODUCER_TOPIC_1=inference-data
    depends_on:
      fastapi-app:
        condition: service_started
      kafka:
        condition: service_healthy
    networks:
      - app-network
    
  # Training Container (consumer/producer)
  train:
    build: ./train_container
    depends_on:
      mlflow:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      - GATEWAY_URL=http://fastapi-app:8000
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - CONSUMER_TOPIC=training-data
      - CONSUMER_GROUP_ID="lstm" # should be changed according to an input argument on container creation
      - PRODUCER_TOPIC=model-training
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    networks:
      - app-network

  # Inference Container (consumer/producer)
  inference:
    build: 
      context: ./inference_container
      dockerfile: Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - GATEWAY_URL=http://fastapi-app:8000
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - CONSUMER_TOPIC_0=inference-data
      - CONSUMER_TOPIC_1=model-training
      - CONSUMER_GROUP_ID=batch-forecasting
      - PRODUCER_TOPIC=performance-eval
    networks:
      - app-network

  
  # Evaluation Service
  evaluator:
    build: ./eval_container
    ports:
      - "8030:8030"
    environment:
      - GATEWAY_URL=http://fastapi-app:8000
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - CONSUMER_TOPIC_0=inference-data
      - CONSUMER_TOPIC_1=performance-eval
      - CONSUMER_GROUP_ID=evaluator
      - PRODUCER_TOPIC=eval-output
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - app-network


# Define the network
networks:
  app-network:
    driver: bridge

volumes:
  minio_data:
  # postgres_data:

  
