apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: preprocess
  name: preprocess
spec:
  ports:
    - name: "{{ .Values.preprocess.service.port }}"
      port: {{ .Values.preprocess.service.port }}
      targetPort: {{ .Values.preprocess.service.port }}
  selector:
    io.kompose.service: preprocess
