apiVersion: batch/v1
kind: Job
metadata:
  labels:
    io.kompose.service: preprocess
  name: preprocess
spec:
  parallelism: {{ .Values.preprocess.job.parallelism }}
  template:
    metadata:
      labels:
        io.kompose.service: preprocess
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.36
          command: ['sh', '-c', 'echo Waiting for Kafka...; while ! nc -z {{ .Values.kafka.service.name }} {{ .Values.kafka.service.port }}; do sleep 1; done; echo Kafka is up!']
      containers:
        - env:
            - name: GATEWAY_URL
              value: {{ .Values.preprocess.env.gatewayURL }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.preprocess.env.kafkaBootstrapServers }}
            - name: PRODUCER_TOPIC_0
              value: {{ .Values.preprocess.env.producerTopic0 }}
            - name: PRODUCER_TOPIC_1
              value: {{ .Values.preprocess.env.producerTopic1 }}
          image: {{ .Values.preprocess.image.repository }}:{{ .Values.preprocess.image.tag }}
          imagePullPolicy: {{ .Values.preprocess.image.pullPolicy }}
          name: preprocess
          ports:
            - containerPort: {{ .Values.preprocess.service.port }}
              protocol: TCP
      restartPolicy: OnFailure
