apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: train
  name: train
spec:
  ports:
    - name: "{{ .Values.train.service.port }}"
      port: {{ .Values.train.service.port }}
      targetPort: {{ .Values.train.service.port }}
  selector:
    io.kompose.service: train
